# 数据源及连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      ###################以下为druid增加的配置###################
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      # 配置获取连接等待超时的时间,单位毫秒
      max-wait: 60000
      # 最小连接池数量
      min-idle: 1
      # 最大连接池数量
      max-active: 100
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 验证连接有效与否的SQL，不同的数据配置不同
      validation-query: select 'x'
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效, 做了这个配置会降低性能, 这里建议配置为TRUE，防止取到的连接不可用
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #  是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      #  在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。如果打开PSCache，建议指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      #  属性类型是字符串，通过别名的方式配置扩展插件，
      #  常用的插件有：监控统计用的filter:stat，日志用的filter:log4j，防御sql注入的filter:wall
      filters: stat,wall
      # 访问的用户名
      loginUsername: admin
      # 访问的密码
      loginPassword: 123456
      # IP黑白名单（共同存在时，deny优先于allow）
      stat-view-servlet:
        allow: 127.0.0.1
        deny: