# Tomcat配置
server:
  port: 8088
  servlet:
    context-path: /demo
  tomcat:
    # 请求编码
    uri-encoding: UTF-8
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 30
    # 等待队列长度，默认100
    accept-count: 1000
    # 最大工作线程数，默认200, 4核8g内存，线程数经验值800
    # 操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好
    max-threads: 1000
    # 最大连接数
    max-connections: 10000
    # 链接建立超时时间
    connection-timeout: 10000



# mysql配置
spring:
  # 环境 dev|test|pro
  profiles:
    active: dev


# mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhu.demo.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator:
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler:
    #自定义SQL注入器
    #sql-injector:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'